### ISSUE TITLE
Think of witty one-liners

### ISSUE THREAD

**Issue by EssamWisam** [JuliaAI/MLJ#1]
- One or more for the MLJ motto that appears in the footer (e.g., A package for elegant and generic machine learning)
- One or more for the model's page (e.g., Over 180 Machine Learning Models...At Your Fingertips)
- One or more for the tutorials page?

CC @ablaom

**Comment by ablaom** [comment]
Thanks @EssamWisam for the work you  are doing behind the scenes on a better landing page for the MLJ project. 

I admit I am not so comfortable with marketing adjectives, like "elegant", and so forth. And when I see a lot of that in other Open Source projects I tend to respond a little cynically.  So you may find my suggestions below a little underwhelming. But I'd like to know what others think about this question of marketing an OS project. 

> One or more for the MLJ motto that appears in the footer (e.g., A package for elegant and generic machine learning)

How about, "A comprehensive machine learning framework for Julia" ? I think "comprehensive" is accurate, and it helps to distinguish from other Julia "machine learning" packages like Flux. 

> One or more for the model's page (e.g., Over 180 Machine Learning Models...At Your Fingertips)

I still like "Model Browser" - that's what it is, right?

**Comment by EssamWisam** [comment]
Of course, any examples I put (whether for the footer, models page or tutorials page) were placeholders. I think `elegant` usually refers to the syntax being clean but I understand the point that it's really a superficial and subjective remark.

I like your recommendation "A comprehensive machine learning framework for Julia". I also had as placeholders:
```
  ["Are you making the right use of your data? Let's find out.", "From pipelines to networks all in one package"]
```
in case you like any of them. The idea is that it's better to have multiple ones (whether for the footer, models page or tutorials page)

**Comment by EssamWisam** [comment]
We resolved this already.
