### ISSUE TITLE
Add links to MLJFlux extended Examples

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJ#17]
When I click on "neural networks" I don't see the two extended examples from the MLJ flux documentation. That is, the MNIST and credit fraud examples.

**Comment by EssamWisam** [comment]
Yes, they have to be added [here](https://github.com/JuliaAI/MLJ/blob/main/src/data/ExternalTutorials.yaml). Let me do it now.

**Comment by EssamWisam** [comment]
Done
