### ISSUE TITLE
List of organizations using MLJ

### ISSUE THREAD

**Issue by EssamWisam** [JuliaAI/MLJ#2]
Will need this for the homepage of the website (point in the future but let's get ready). The idea is that it can be rolling carousel of logos. Finding at least six would be optimal in this case. Surely alright to include universities.

CC: @ablaom

**Comment by ablaom** [comment]
I admit I don't have a good sense of this. We might need some kind of survey. In the past we did collect testimonials, but unless pressed, users don't seem to want to volunteer their affiliations. You could glean something about the application but not the company.  I assume we need permission of the company to list them.

We do know for a fact that IQVIA (healthcare consultancy) is using MLJ, and they provided financial support for the project at one point. The other logos on the homepage reflect academic supporters/funders.

**Comment by EssamWisam** [comment]
How is it coming?

**Comment by EssamWisam** [comment]
Closing as its trivial to add any additional organizations via https://github.com/JuliaAI/MLJ/blob/main/src/data/HomePage.yaml. If a number of testimonials is present in the future, I would be happy to add a section for that (but that would be future work).
